class Elements:
    nav_search = '//*[@id="twotabsearchtextbox"]'
    departments = '//*[@id="departments"]/ul/li[11]/span/div/a/span'
    toys_departments = '// *[ @ id = "n/165793011"] / span / a / span'
    select_next_button = '//li[@class="a-last"]/a'
    select_item = '/html/body/div[1]/div[2]/div[1]/div[2]/div/span[3]/div[2]/div[2]/div/span/div/div/div/div/span/a/div'
    item_price = '//span[@id="price_inside_buybox"]'
    select_value_options = '//ul[@class="a-nostyle a-list-link"]/li'
    quantity_dropdown = '//*[@id="selectQuantity"]/span/div/div/span'
    dropdown_option = '//*[@id="quantity_{0}"]'
    product_title = '//*[@id="productTitle"]'
    add_to_cart = '//*[@id="add-to-cart-button"]'
    cart_button = '//*[@id="hlb-view-cart-announce"]'
    subtotal_amount = '//*[@id="sc-subtotal-amount-activecart"]/span'
    cart_product_title = 'span.sc-product-title'
